#pragma once

#ifdef __cplusplus
extern "C" {
#endif

#include "dbccodeconf.h"

#include "hytech.h"

typedef struct
{
  TCU_DRIVER_MSG_t TCU_DRIVER_MSG;
  TCU_LAP_TIMES_t TCU_LAP_TIMES;
  MC1_STATUS_t MC1_STATUS;
  MC2_STATUS_t MC2_STATUS;
  MC3_STATUS_t MC3_STATUS;
  MC4_STATUS_t MC4_STATUS;
  MC1_TEMPS_t MC1_TEMPS;
  MC2_TEMPS_t MC2_TEMPS;
  MC3_TEMPS_t MC3_TEMPS;
  MC4_TEMPS_t MC4_TEMPS;
  MC1_ENERGY_t MC1_ENERGY;
  MC2_ENERGY_t MC2_ENERGY;
  MC3_ENERGY_t MC3_ENERGY;
  MC4_ENERGY_t MC4_ENERGY;
  MC1_SETPOINTS_COMMAND_t MC1_SETPOINTS_COMMAND;
  MC2_SETPOINTS_COMMAND_t MC2_SETPOINTS_COMMAND;
  MC3_SETPOINTS_COMMAND_t MC3_SETPOINTS_COMMAND;
  MC4_SETPOINTS_COMMAND_t MC4_SETPOINTS_COMMAND;
  MC1_TORQUE_COMMAND_t MC1_TORQUE_COMMAND;
  MC2_TORQUE_COMMAND_t MC2_TORQUE_COMMAND;
  MC3_TORQUE_COMMAND_t MC3_TORQUE_COMMAND;
  MC4_TORQUE_COMMAND_t MC4_TORQUE_COMMAND;
  MCU_STATUS_t MCU_STATUS;
  MCU_PEDAL_READINGS_t MCU_PEDAL_READINGS;
  MCU_LOAD_CELLS_t MCU_LOAD_CELLS;
  SAB_LOAD_CELLS_t SAB_LOAD_CELLS;
  MCU_FRONT_POTS_t MCU_FRONT_POTS;
  MCU_REAR_POTS_t MCU_REAR_POTS;
  MCU_ANALOG_READINGS_t MCU_ANALOG_READINGS;
  BMS_ONBOARD_TEMPS_t BMS_ONBOARD_TEMPS;
  BMS_ONBOARD_DETAILED_TEMPS_t BMS_ONBOARD_DETAILED_TEMPS;
  BMS_VOLTAGES_t BMS_VOLTAGES;
  BMS_DETAILED_VOLTAGES_t BMS_DETAILED_VOLTAGES;
  BMS_TEMPS_t BMS_TEMPS;
  BMS_DETAILED_TEMPS_t BMS_DETAILED_TEMPS;
  BMS_STATUS_t BMS_STATUS;
  CCU_STATUS_t CCU_STATUS;
  BMS_BALANCING_STATUS_t BMS_BALANCING_STATUS;
  BMS_COULOMB_COUNTS_t BMS_COULOMB_COUNTS;
  DASHBOARD_MCU_STATE_t DASHBOARD_MCU_STATE;
  DASHBOARD_STATE_t DASHBOARD_STATE;
  EM_STATUS_t EM_STATUS;
  EM_MEASUREMENT_t EM_MEASUREMENT;
  CHARGER_CONTROL_t CHARGER_CONTROL;
  CHARGER_DATA_t CHARGER_DATA;
} hytech_rx_t;

// There is no any TX mapped massage.

uint32_t hytech_Receive(hytech_rx_t* m, const uint8_t* d, uint32_t msgid, uint8_t dlc);

#ifdef __DEF_HYTECH__

extern hytech_rx_t hytech_rx;

#endif // __DEF_HYTECH__

#ifdef __cplusplus
}
#endif
